server:
    port: 8081

spring:
    profiles:
        active: prod
    data:
        mongodb:
            host: localhost
            port: 27017
            database: cam
files:
    tmpTimeout: 7200000

