server:
    port: 8082

spring:
    profiles:
        active: prod
files:
    tmpTimeout: 7200000

sites:
    petsroom:
        db:
            host: mongo
            port: 27017
            database: petsroom
