# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false
upload:
    maxFileSize: 1024MB

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    messageSource:
        cacheSeconds: 1

