server:
    port: 8081

spring:
    profiles:
        active: dev
files:
    tmpTimeout: 7200000

sites:
    petsroom:
        db:
            host: localhost
            port: 27017
            database: cam

